name: clock-in

on:
  schedule:
    - cron: '30 11 * * *'

  workflow_dispatch:

jobs:
  Clock_in:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - run: pip3 install -r requirements.txt

      - run: python clock_in.py
